version: '3.9'

services:
  fastapi-app:
    build:
      context: . 
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    restart: always
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.4
    ports:
      - "3307:3306"
    environment:
       MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    
volumes:
  mysql-data:

